[FIX] account: handle error when incorrect domain is passed in account report
When user gives wrong domain in any account report of report line and tries
to access the same report similar error is generated.

Steps to Produce:
- Install 'Accounting'
- Go to Accounting > Configuration > Accounting Reports
- Open any account report and click on add a line
- Now add a line in the report line
- Create an expression select 'Computation Engine' as Odoo Domain.
- In Formula add this domain [('code', '!=like', '620.%')]
- And add Sub-Formula as 'sum'
- Save the expression and also the report
- Go to Reporting and select the above report

Traceback will be generated

ValueError: Invalid leaf ('code', '!=like', '620.%')

When user applies invalid values in domain or invalid domain format it leads
to the traceback because of this line:
https://github.com/odoo/enterprise/blob/16.0/account_reports/models/account_report.py#L1510

sentry-4358342635

closes odoo/odoo#130981

Signed-off-by: John Laterre (jol) <jol@odoo.com>